name:                plainledger
version:             0.1.0.0
github:              "archambaultv/plainledger"
license:             OtherLicense # OBSD
author:              "Vincent Archambault-Bouffard"
maintainer:          "archambault.v@gmail.com"
copyright:           "2019 Vincent Archambault-Bouffard"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Simple plain text accounting program
category:            Finance

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/archambaultv/plainledger#readme>

dependencies:
- base >= 4.7 && < 5
- time
- containers
- text
- megaparsec
- Decimal
- optparse-applicative
- mtl
- cassava
- bytestring
- sexpresso
- parser-combinators
- recursion-schemes
- bifunctors

ghc-options:
  - -Wall
  
library:
  source-dirs: src

executables:
  plainledger:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - plainledger

tests:
  plainledger-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - plainledger
